name: poker-vm
services:
  - name: poker-vm-ui
    type: static-site
    build_command: yarn build
    output_dir: build
    catchall_document: index.html
    routes:
      - path: /assets/*
        preserve_path_prefix: true
      - path: /static/*
        preserve_path_prefix: true
      - path: /*
        rewrite: /index.html
    envs:
      - key: REACT_APP_PROXY_URL
        value: https://proxy.block52.xyz
      - key: VITE_APP_TITLE
        scope: BUILD_TIME
      - key: VITE_APP_DESCRIPTION
        scope: BUILD_TIME
      - key: VITE_APP_URL
        scope: BUILD_TIME
      - key: VITE_APP_DOMAIN
        scope: BUILD_TIME
      - key: VITE_APP_IMAGE
        scope: BUILD_TIME